### ISSUE TITLE
Replace the HashRouter with BrowserRouter

### ISSUE THREAD

**Issue by krook** [openeew/openeew-dashboard#28]
We're currently using `HashRouter` in https://github.com/openeew/openeew-dashboard/blob/master/web/client/src/Router.js#L7

Personally I'd prefer to use `BrowserRouter` as with the Prometeo dashboard so we have clean URLs:
https://github.com/Call-for-Code/Prometeo-Dashboard/blob/master/prometeo-dashboard/src/App.js#L20

I'm not sure if anyone else has a strong opinion. @rdkelley @JohnyTheCarrot?

**Comment by rdkelley** [comment]
Definitely BrowserRouter -- I put HashRouter in there initially since the Carbon docs said BrowserRouter requires a bit more configuration to work on Cloud Foundry. But we should switch to BrowserRouter soon.

**Comment by JohnyTheCarrot** [comment]
Whoops, missed this. No strong opinion. BrowserRouter is what I usually use.

**Comment by krook** [comment]
Closing based on merger of #39. Thanks @JohnyTheCarrot!
