### ISSUE TITLE
Add new account setup flow

### ISSUE THREAD

**Issue by rdkelley** [openeew/openeew-dashboard#6]
- [x] Add API routes to handle onboarding
- [ ] Add UI

**Comment by karsingh991** [comment]
Hi @rdkelley, Let me know if i can can help here. I want to contribute as well.

**Comment by rdkelley** [comment]
Hi @karsingh991. Absolutely, we would love the help! However, we need to update this roadmap a bit because authentication from the front end was already added and how it fits in with a backend service is part of the architecture we're trying to plan out now. There are also most likely some significant changes to the current repo coming soon. Almost all of our planning and assignments happen on our [OpenEEW slack channel](https://openeew.com/) -- if you're not already signed up for that, that's the best place to get involved.
